### ISSUE TITLE
API authorisation issue

### ISSUE THREAD

**Issue by tpapz-be** [isleshocky77/ninja-forms-mautic#4]
Hello, 

I am faced with the below error when I try to authorise the plugin. 
I tried OAuth1a and OAuth2.
API settings have been set on my Mautic and HTTP auth is authorized. 
I've downloaded the plugin here and installed it through WP plugin uploader/installer. 

The issue seems related to ApiAuth but not sure how to fix it. 

Any idea ? Many thanks in advance - 

--------
WordPress version 5.4.1
Current theme: Terra Fermenta (version 1.0.0)
Current plugin: Ninja Forms - Mautic (version 3.1.2)
PHP version 7.3.17

Error Details
=============
An error of type E_ERROR was caused in line 136 of the file /data/sites/web/terrafermentacom/www/wp-content/plugins/ninja-forms-mautic-master/includes/Admin/Settings.php. Error message: Uncaught Error: Class 'Mautic\Auth\ApiAuth' not found in /data/sites/web/terrafermentacom/www/wp-content/plugins/ninja-forms-mautic-master/includes/Admin/Settings.php:136
Stack trace:
#0 /data/sites/web/terrafermentacom/www/wp-includes/class-wp-hook.php(287): NF_Mautic_Admin_Settings->authorize_setting('1')
#1 /data/sites/web/terrafermentacom/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /data/sites/web/terrafermentacom/www/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /data/sites/web/terrafermentacom/www/wp-content/plugins/ninja-forms/includes/Admin/Menus/Settings.php(254): do_action('ninja_forms_sav...', '1')
#4 /data/sites/web/terrafermentacom/www/wp-includes/class-wp-hook.php(287): NF_Admin_Menus_Settings->update_settings('')
#5 /data/sites/web/terrafermentacom/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#6 /data/sites/web/terrafermentacom/www/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /data/sites/web/terrafermentaco

**Comment by pfaraluce** [comment]
Same error here. Any guesses on how to fix this? Thanks
